### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by Gunthermic** [MatthewBooth/OTAUpdates#35]
Addons Force Close upon opening now. Catlog sent..

**Comment by MatthewBooth** [comment]
Just for future ref, @Gunthermic , you should post the logcat data if you can. Always search the log for "FATAL EXCEPTION" and post the error it finds. Usually the best way :) I only say this so that others might find the log through Google or the like and get help later on.

I think I know what the issue here is, so I'll have a go tonight.

**Comment by Gunthermic** [comment]
Sorry sir
