### ISSUE TITLE
Android 6.0

### ISSUE THREAD

**Issue by XrTV** [MatthewBooth/OTAUpdates#65]
Please add support for Android 6.0, and on romhut, too.

**Comment by scottrobertson** [comment]
Open a ticket for romhut here: https://github.com/romhut/romhut.com

**Comment by MatthewBooth** [comment]
Check out the develop branch. This app is in full rewrite at the moment. Does the 2.5.3 version not work at all on Marshmallow?

**Comment by XrTV** [comment]
To work - works. But not version 6.0.

**Comment by MatthewBooth** [comment]
I don't see any reason why it wouldn't work on v6.0, but I will compile a fresh version tonight with support. You can also just hack the apk using apktool to accept 6.0 in the mean time. That should work. I'm wanting to devote all time to the rewrite at the moment.

**Comment by smeroni68** [comment]
Hi Matt,
on MM (checking logs) seems that the check of a new version available is getting (probably) some network access problems, and the OTA info (present in the rom) seems like not used correctly.
We removed OTA Updateds apk from our MM roms due to this, but would be great if it can be fixed.
If you need any log, just let me know and we will provide.
Thanks mate.
